create database eduschema;
use eduschema;
create table department(d_id int primary key , d_name varchar(40));
create table course(c_id int primary key , c_name varchar(50) not null , credits int not null , d_id int references department(d_id));
create table student(s_id int primary key , s_name varchar(50) not null , s_dob date not null , s_address varchar(100) not null , s_phone varchar(10) not null , s_email varchar(40) not null , en_date date not null , gender varchar(1)  not null ,d_id int references department(d_id));
create table instructor(i_id int primary key , i_name varchar(40) not null , i_dob date not null , i_address varchar(100) not null , i_phone varchar(10) not null , i_email varchar(40) not null ,gender varchar(1)  not null , qualifications varchar(30) not null ,  joining_date date not null ,salary decimal(7,2) not null  , experience int not null );
create table section(sec_id int primary key , year int(4) not null , section varchar(1) not null , c_id int references course(c_id) , i_id int references instructor(i_id));
create table grades(gr_id int primary key , grades int not null , grading_date date not null , s_id int references student(s_id) , sec_id int references section(sec_id));
create table enrollment(en_id int primary key , sec_id int references section(sec_id), s_id int references student(s_id));
create table teaching(t_id int primary key , i_id int references instructor(i_id) , s_id int references student(s_id));
alter table department drop column d_id;
alter table student drop column s_id;
alter table instructor drop column i_id;
alter table section drop column sec_id;
alter table grades drop column gr_id;
alter table enrollment drop column en_id;
alter table course drop column c_id;
alter table teaching drop column t_id;
alter table department add column d_id int auto_increment primary key ;
alter table student add column s_id int auto_increment primary key ;
alter table instructor add column i_id int auto_increment primary key ;
alter table section add column sec_id int auto_increment primary key ;
alter table grades add column gr_id int auto_increment primary key ;
alter table enrollment add column en_id int auto_increment primary key ;
alter table teaching add column t_id int auto_increment primary key ;
alter table course add column c_id int auto_increment primary key ;
insert into student values("Divyanshu","2002-08-26","64 adarsh krishna nagar","729697736","droan@gmail.com","2024-06-20","M",002,001);
alter table department add column is_deleted varchar(5) check(is_deleted in ("Yes","No")) ;
alter table student add column is_deleted varchar(5) check(is_deleted in ("Yes","No")) ;
alter table instructor add column is_deleted varchar(5) check(is_deleted in ("Yes","No")) ;
alter table  grades add column is_deleted varchar(5) check(is_deleted in ("Yes","No")) ;
alter table course add column is_deleted varchar(5) check(is_deleted in ("Yes","No")) ;
alter table course modify column is_deleted varchar(5) check(is_deleted in ("Yes","No"))  default "No";
alter table department modify column is_deleted varchar(5) check(is_deleted in ("Yes","No"))  default "No";
alter table student modify column is_deleted varchar(5) check(is_deleted in ("Yes","No"))  default "No";
alter table instructor modify column is_deleted varchar(5) check(is_deleted in ("Yes","No"))  default "No";
alter table grades modify column is_deleted varchar(5) check(is_deleted in ("Yes","No"))  default "No";
select * from student;
select * from department;
select * from course;
select * from instructor;
select * from section;
select * from teaching;
select * from grades;
select * from enrollment;
select * from grades where is_deleted = "No";
update course set is_deleted ="Yes" where c_id=1;
alter table instructor modify column gender varchar(5) not null ;
alter table student modify column gender varchar(5) not null ;
create table users(u_id int primary key auto_increment , u_name varchar(30) not null , pass_hash varchar(30) not null );
alter table users modify column u_name varchar(200) not null ;
alter table users modify column pass_hash varchar(200) not null ;
select * from users;